# NumPy

Numpy is general purpose array processing package. It is the fundamental package for scintific calculation/ computing with python . 

In [2]:
# Import numPy library

import numpy as np


In [9]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)
type(arr)

numpy.ndarray

In [11]:
print(arr)

[1 2 3 4 5]


In [10]:
arr.shape

(5,)

In [12]:
arr

array([1, 2, 3, 4, 5])

In [6]:
l1= [1,2,3,4]
l2= [5,6,7,8]
l3= [9,10,11,12]

list = [l1,l2,l3]
type(list)



list

In [7]:
arr = np.array([l1,l2,l3])
type(arr)

numpy.ndarray

In [8]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr.shape

In [ ]:
arr.reshape(4,3)

In [ ]:
arr.shape

# Indexing


In [ ]:
# Retrive the data from Array
l1= [1,2,3,4]
l2= [5,6,7,8]
l3= [9,10,11,12]
arr = np.array([l1,l2,l3])


In [ ]:
arr[2]

In [ ]:
arr

In [ ]:
arr[:,:]

In [ ]:
arr[0:2,0:2]

In [ ]:
arr[1:,1:3]

In [ ]:
arr[1:2,0:3]

In [ ]:
arr =np.arange(0,10)
arr

In [ ]:
arr = np.arange(0,10,step=2)
arr

In [15]:
arr = np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [22]:
## copy() function and broadcasting
arr[3:]=100

In [14]:
arr

array([  1,   2,   3, 100, 100])

In [16]:
arr1 = arr

In [19]:
arr1[3:] = 500
print(arr1)

[  1.           1.18367347   1.36734694 500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.        ]


In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
ran_ex=np.random.randn(4,4)
ran_ex

array([[-0.34730772, -0.08823511,  0.23444257,  1.04245944],
       [-0.68031015, -0.92732674, -0.21662858, -0.45989785],
       [ 0.09702401,  0.40059329, -1.11270358, -1.70512901],
       [ 1.37419785, -0.2727711 ,  1.01747233, -0.01061273]])